// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1PYevclxt1qxJBAacjC_qzXfWFnQsov0',
    appId: '1:894308179973:web:a87d10da32da16c0f33c6c',
    messagingSenderId: '894308179973',
    projectId: 'cardapio-k1',
    authDomain: 'cardapio-k1-c3881.firebaseapp.com',
    databaseURL: 'https://cardapio-k1-default-rtdb.firebaseio.com',
    storageBucket: 'cardapio-k1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp2BMUQFATtC1BOQMlttlr58faCxOBbrQ',
    appId: '1:894308179973:android:39bd3d8379152403f33c6c',
    messagingSenderId: '894308179973',
    projectId: 'cardapio-k1',
    databaseURL: 'https://cardapio-k1-default-rtdb.firebaseio.com',
    storageBucket: 'cardapio-k1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgbf66b_FgPR1e_VuYSxDaIVEbLfawkTw',
    appId: '1:894308179973:ios:52cf665c7731c394f33c6c',
    messagingSenderId: '894308179973',
    projectId: 'cardapio-k1',
    databaseURL: 'https://cardapio-k1-default-rtdb.firebaseio.com',
    storageBucket: 'cardapio-k1.appspot.com',
    iosBundleId: 'com.example.k1Cardapio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgbf66b_FgPR1e_VuYSxDaIVEbLfawkTw',
    appId: '1:894308179973:ios:6c904d579636ee8af33c6c',
    messagingSenderId: '894308179973',
    projectId: 'cardapio-k1',
    databaseURL: 'https://cardapio-k1-default-rtdb.firebaseio.com',
    storageBucket: 'cardapio-k1.appspot.com',
    iosBundleId: 'com.example.k1Cardapio.RunnerTests',
  );
}
